name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

  security-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      # Ejecuta cada prueba de seguridad individualmente
      - name: CommentControllerSecurityTest
        run: mvn -Dtest=CommentControllerSecurityTest test

      - name: PlaceControllerSecurityTest
        run: mvn -Dtest=PlaceControllerSecurityTest test

      - name: PostControllerSecurityTest
        run: mvn -Dtest=PostControllerSecurityTest test

      - name: PromotionControllerSecurityTest
        run: mvn -Dtest=PromotionControllerSecurityTest test

      - name: ReservationControllerSecurityTest
        run: mvn -Dtest=ReservationControllerSecurityTest test

      - name: ReviewControllerSecurityTest
        run: mvn -Dtest=ReviewControllerSecurityTest test

      - name: UserControllerSecurityTest
        run: mvn -Dtest=UserControllerSecurityTest test

 
