name: tests

on:
  push:
    branches:
      - main  # Cambia 'main' por la rama en la que quieres que se ejecute (por ejemplo, 'master' o cualquier otra rama).
  pull_request:
    branches:
      - main  # También se ejecutará en los pull requests.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21' 
          distribution: 'temurin"

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and Test
        run: mvn clean verify 
