name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

  security-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run Security Tests
        run: mvn -Dtest=*ControllerSecurityTest test
        # Ejecuta solo los tests de seguridad (ajusta el patrón según el nombre de tus tests)

      - name: 📄 Upload Test Results 
        if: always()  # Ejecuta este paso sin importar si los tests pasan o fallan
        uses: actions/upload-artifact@v2
        with:
          name: security-test-results
          path: target/surefire-reports  # Carpeta donde Maven guarda los reportes de tests
