name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job para configurar el entorno de build general
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21' 
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

  # Job específico para tests de seguridad
  security-tests:
    runs-on: ubuntu-latest
    needs: build  # Ejecuta este job después del job de "build"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21' 
          distribution: 'temurin'

      - name: Run Security Tests
        run: mvn -Dtest=CommentControllerSecurityTest,PlaceControllerSecurityTest,PostControllerSecurityTest,PromotionControllerSecurityTest,ReservationControllerSecurityTest,ReviewControllerSecurityTest,UserControllerSecurityTest test
        # Agrega aquí los nombres de las clases de prueba de seguridad que deseas ejecutar

  # Job para otros tests (por ejemplo, tests unitarios o de integración)
  other-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21' 
          distribution: 'temurin'

      - name: Run Other Tests
        run: mvn -Dtest=!CommentControllerSecurityTest,!PlaceControllerSecurityTest,!PostControllerSecurityTest,!PromotionControllerSecurityTest,!ReservationControllerSecurityTest,!ReviewControllerSecurityTest,!UserControllerSecurityTest test
        # Este comando excluye los tests de seguridad para que solo se ejecuten los demás tests

