name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21' 
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

  security-tests:
    runs-on: ubuntu-latest
    needs: build 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21' 
          distribution: 'temurin'

      - name: Run Security Tests
        run: mvn -Dtest=CommentControllerSecurityTest,PlaceControllerSecurityTest,PostControllerSecurityTest,PromotionControllerSecurityTest,ReservationControllerSecurityTest,ReviewControllerSecurityTest,UserControllerSecurityTest test

  other-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21' 
          distribution: 'temurin'

      - name: Run Other Tests
        run: mvn -Dtest=!CommentControllerSecurityTest,!PlaceControllerSecurityTest,!PostControllerSecurityTest,!PromotionControllerSecurityTest,!ReservationControllerSecurityTest,!ReviewControllerSecurityTest,!UserControllerSecurityTest test

