name: Autograding Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'explore-connect[bot]'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run all Repository Tests
        id: run_tests
        run: |
          mvn test -Dtest=dbp.exploreconnet.user.infrastructure.UserRepositoryTest
          mvn test -Dtest=dbp.exploreconnet.place.infrastructure.PlaceRepositoryTest
          mvn test -Dtest=dbp.exploreconnet.reservation.infrastructure.ReservationRepositoryTest
          mvn test -Dtest=dbp.exploreconnet.review.infrastructure.ReviewRepositoryTest
          mvn test -Dtest=dbp.exploreconnet.promotion.infrastructure.PromotionRepositoryTest

      - name: Display Test Results
        run: mvn surefire-report:report

  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Create PROJECT_KEY
        env:
          REPO_NAME: ${{github.repositoryUrl}}
        run: echo "PROJECT_KEY=$(echo '${{env.REPO_NAME}}'| sed -n 's/.*\/lab-e2e-20241-04-\(.*\)\.git/\1/p')" >> $GITHUB_ENV

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          PROJECT_KEY: ${{ env.PROJECT_KEY }}
        run: mvn -B verify -DskipTests=true org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=${{env.PROJECT_KEY}} -Dsonar.projectName=${{env.PROJECT_KEY}}
